// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockIMathService creates a new instance of MockIMathService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIMathService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIMathService {
	mock := &MockIMathService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIMathService is an autogenerated mock type for the IMathService type
type MockIMathService struct {
	mock.Mock
}

type MockIMathService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIMathService) EXPECT() *MockIMathService_Expecter {
	return &MockIMathService_Expecter{mock: &_m.Mock}
}

// FormatNumber provides a mock function for the type MockIMathService
func (_mock *MockIMathService) FormatNumber(num float64, base int) (string, error) {
	ret := _mock.Called(num, base)

	if len(ret) == 0 {
		panic("no return value specified for FormatNumber")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(float64, int) (string, error)); ok {
		return returnFunc(num, base)
	}
	if returnFunc, ok := ret.Get(0).(func(float64, int) string); ok {
		r0 = returnFunc(num, base)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(float64, int) error); ok {
		r1 = returnFunc(num, base)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIMathService_FormatNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FormatNumber'
type MockIMathService_FormatNumber_Call struct {
	*mock.Call
}

// FormatNumber is a helper method to define mock.On call
//   - num
//   - base
func (_e *MockIMathService_Expecter) FormatNumber(num interface{}, base interface{}) *MockIMathService_FormatNumber_Call {
	return &MockIMathService_FormatNumber_Call{Call: _e.mock.On("FormatNumber", num, base)}
}

func (_c *MockIMathService_FormatNumber_Call) Run(run func(num float64, base int)) *MockIMathService_FormatNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(float64), args[1].(int))
	})
	return _c
}

func (_c *MockIMathService_FormatNumber_Call) Return(s string, err error) *MockIMathService_FormatNumber_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockIMathService_FormatNumber_Call) RunAndReturn(run func(num float64, base int) (string, error)) *MockIMathService_FormatNumber_Call {
	_c.Call.Return(run)
	return _c
}

// Product provides a mock function for the type MockIMathService
func (_mock *MockIMathService) Product(numbers []float64) (float64, error) {
	ret := _mock.Called(numbers)

	if len(ret) == 0 {
		panic("no return value specified for Product")
	}

	var r0 float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]float64) (float64, error)); ok {
		return returnFunc(numbers)
	}
	if returnFunc, ok := ret.Get(0).(func([]float64) float64); ok {
		r0 = returnFunc(numbers)
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func([]float64) error); ok {
		r1 = returnFunc(numbers)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIMathService_Product_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Product'
type MockIMathService_Product_Call struct {
	*mock.Call
}

// Product is a helper method to define mock.On call
//   - numbers
func (_e *MockIMathService_Expecter) Product(numbers interface{}) *MockIMathService_Product_Call {
	return &MockIMathService_Product_Call{Call: _e.mock.On("Product", numbers)}
}

func (_c *MockIMathService_Product_Call) Run(run func(numbers []float64)) *MockIMathService_Product_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]float64))
	})
	return _c
}

func (_c *MockIMathService_Product_Call) Return(f float64, err error) *MockIMathService_Product_Call {
	_c.Call.Return(f, err)
	return _c
}

func (_c *MockIMathService_Product_Call) RunAndReturn(run func(numbers []float64) (float64, error)) *MockIMathService_Product_Call {
	_c.Call.Return(run)
	return _c
}

// Round provides a mock function for the type MockIMathService
func (_mock *MockIMathService) Round(num float64) float64 {
	ret := _mock.Called(num)

	if len(ret) == 0 {
		panic("no return value specified for Round")
	}

	var r0 float64
	if returnFunc, ok := ret.Get(0).(func(float64) float64); ok {
		r0 = returnFunc(num)
	} else {
		r0 = ret.Get(0).(float64)
	}
	return r0
}

// MockIMathService_Round_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Round'
type MockIMathService_Round_Call struct {
	*mock.Call
}

// Round is a helper method to define mock.On call
//   - num
func (_e *MockIMathService_Expecter) Round(num interface{}) *MockIMathService_Round_Call {
	return &MockIMathService_Round_Call{Call: _e.mock.On("Round", num)}
}

func (_c *MockIMathService_Round_Call) Run(run func(num float64)) *MockIMathService_Round_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(float64))
	})
	return _c
}

func (_c *MockIMathService_Round_Call) Return(f float64) *MockIMathService_Round_Call {
	_c.Call.Return(f)
	return _c
}

func (_c *MockIMathService_Round_Call) RunAndReturn(run func(num float64) float64) *MockIMathService_Round_Call {
	_c.Call.Return(run)
	return _c
}

// Sum provides a mock function for the type MockIMathService
func (_mock *MockIMathService) Sum(numbers []float64) float64 {
	ret := _mock.Called(numbers)

	if len(ret) == 0 {
		panic("no return value specified for Sum")
	}

	var r0 float64
	if returnFunc, ok := ret.Get(0).(func([]float64) float64); ok {
		r0 = returnFunc(numbers)
	} else {
		r0 = ret.Get(0).(float64)
	}
	return r0
}

// MockIMathService_Sum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sum'
type MockIMathService_Sum_Call struct {
	*mock.Call
}

// Sum is a helper method to define mock.On call
//   - numbers
func (_e *MockIMathService_Expecter) Sum(numbers interface{}) *MockIMathService_Sum_Call {
	return &MockIMathService_Sum_Call{Call: _e.mock.On("Sum", numbers)}
}

func (_c *MockIMathService_Sum_Call) Run(run func(numbers []float64)) *MockIMathService_Sum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]float64))
	})
	return _c
}

func (_c *MockIMathService_Sum_Call) Return(f float64) *MockIMathService_Sum_Call {
	_c.Call.Return(f)
	return _c
}

func (_c *MockIMathService_Sum_Call) RunAndReturn(run func(numbers []float64) float64) *MockIMathService_Sum_Call {
	_c.Call.Return(run)
	return _c
}
